### ISSUE TITLE
int fields are rendered as floating points numbers

### ISSUE THREAD

**Issue by adamsiemion** [LemonSoftware/angularjs-addon#1]
The `age` field from the sample application has type `int` but is rendered as a floating point number [see](https://raw.githubusercontent.com/LemonSoftware/extjs-addon/webpage/hello-extjs-screen.png)

**Comment by mohhmekk** [comment]
Fixed, integers and long will be rendered without decimals.
![screen shot 2015-01-22 at 20 19 02](https://cloud.githubusercontent.com/assets/7027075/5861640/095e9920-a274-11e4-818a-23c07a536327.png)
